services:
  db:
    build:
      context: ./requirements/MariaDB
    image: mariadb:jett
    container_name: mariadb
    environment:
      MARIADB_db: ${MARIADB_db}
      MARIADB_user: ${MARIADB_user}
      MARIADB_password: ${MARIADB_password}
      MARIADB_host: ${MARIADB_host}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wordpress_network
    restart: unless-stopped

  wordpress:
    build: 
      context: ./requirements/WordPress
    image: wordpress:jett
    container_name: wordpress
    environment:
      MARIADB_db: ${MARIADB_db}
      MARIADB_user: ${MARIADB_user}
      MARIADB_password: ${MARIADB_password}
      MARIADB_host: ${MARIADB_host}
      url: ${url}
      title: ${title}
      admin_user: ${admin_user}
      admin_password: ${admin_password}
      admin_email: ${admin_email}

    volumes:
      - wordpress_data:/var/www/html
    networks:
      - wordpress_network
    restart: unless-stopped
    depends_on:
      - db
    
  nginx:
    build:
      context: ./requirements/Nginx
    image: nginx:jett
    container_name: nginx
    ports:
      - "4443:443"
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - wordpress_network
    restart: unless-stopped
    depends_on:
      - wordpress


volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/sel-jett/goinfre/volumes/wordpress
      o: bind
  db_data:
    driver: local
    driver_opts:
      type: none
      device: /home/sel-jett/goinfre/volumes/mariadb
      o: bind

networks:
  wordpress_network:
    driver: bridge