services:
  db:
    build:
      context: ./requirements/MariaDB
    image: mariadb:jett
    container_name: mariadb
    environment:
      MARIADB_db: wordpress
      MARIADB_user: salah
      MARIADB_password: '123456789'
      MARIADB_host: mariadb
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wordpress_network
    restart: unless-stopped

  wordpress:
    build: 
      context: ./requirements/WordPress
    image: wordpress:jett
    container_name: wordpress
    environment:
      MARIADB_db: wordpress
      MARIADB_user: salah
      MARIADB_password: '123456789'
      MARIADB_host: mariadb
      url: 'https://localhost:4443'
      title: 'jett'
      admin_user: '7loban'
      admin_password: 'sakserbellak'
      admin_email: '7loban@gmail.com'

    volumes:
      - wordpress_data:/var/www/html
    networks:
      - wordpress_network
    restart: unless-stopped
    depends_on:
      - db
    
  nginx:
    build:
      context: ./requirements/Nginx
    image: nginx:jett
    container_name: nginx
    ports:
      - "4443:443"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - wordpress_network
    restart: unless-stopped
    depends_on:
      - wordpress


volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/sel-jett/goinfre/volumes/wordpress
      o: bind
  db_data:
    driver: local
    driver_opts:
      type: none
      device: /home/sel-jett/goinfre/volumes/mariadb
      o: bind

networks:
  wordpress_network:
    driver: bridge