services:

  nginx:
    build:
      context: ./src/Nginx
    ports:
      - "443:443"
    
  wordpress:
    build: 
      context: ./src/WordPress
    env_file:
      - .env
    ports:
      - "9000:9000"
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - db

  db:
    image: mariadb:latest
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress_user
      - MYSQL_PASSWORD=your_secure_password
      - MYSQL_ROOT_PASSWORD=your_secure_root_password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  wordpress_data:
  db_data: 