services:
  db:
    build:
      context: ./src/MariaDB
    container_name: mariadb
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wordpress_network

  wordpress:
    build: 
      context: ./src/WordPress
    container_name: wordpress
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - wordpress_network
    depends_on:
      - db
    
  nginx:
    build:
      context: ./src/Nginx
    container_name: nginx
    ports:
      - "4443:443"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - wordpress_network
    depends_on:
      - wordpress


volumes:
  wordpress_data:
  db_data:

networks:
  wordpress_network:
    driver: bridge